name: Build website
run-name: Build Vite
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository code
        uses: actions/checkout@v4
      - name: Build the website
        run: |
          cd ${{ github.workspace }}
          cd website
          npm install
          npm run build
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_dir: ${{ github.workspace }}/website/dist 
          github_token: ${{ secrets.GITHUB_TOKEN }}
